#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changed() {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'pnpm-lock.yaml'; then
  echo "pnpm-lock.yaml has changed. Running pnpm install to bring your dependencies up to date."
  pnpm install
fi
